[package]
name = "mahou"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "1.1.2"
sha2 = "0.11.0"
hex = "0.4.3"
reqwest = { version = "0.12.2", default-features = false, features = ["blocking", "rustls-tls"] }
regex = "1"
ratatui = "0.30.0"
crossterm = "0.29.0"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
