name = "giflib"
version = "5.2.2"
description = "Library to handle, display and manipulate GIF images"
source = "https://downloads.sourceforge.net/giflib/giflib-5.2.2.tar.gz"
sha256 = "be7ffbd057cadebe2aa144542fd90c6838c6a083b5e8a9048b8ee3b66b29d5fb"
source_dir = "giflib-5.2.2"
deps = []

build_steps = [
  "make",
  "make PREFIX=/usr DESTDIR=${MAHOU_DESTDIR} install",
]
