name = "pam"
version = "1.7.2"
description = "Linux-PAM (Pluggable Authentication Modules)"
source = "https://github.com/linux-pam/linux-pam/archive/e634a3a9be9484ada6e93970dfaf0f055ca17332.tar.gz"
sha256 = "91fb6bf9a52e16a859181ae9be5dc989d8dfdb45d2d4e6816648709342ccff57"
source_dir = "Linux-${PN^^}-1.7.2"
deps = ["libxcrypt"]

build_steps = [
  "meson setup build --prefix=/usr --buildtype=release",
  "ninja -C build",
  "DESTDIR=${MAHOU_DESTDIR} ninja -C build install",
]
